import "./globals.css";

export const metadata = {
  title: "Average Boring Website Interface - Wahyu Syamsul A'lam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-rose-50/50 text-[#916E74]  min-h-screen">
        {children}
      </body>
    </html>
  );
}
